version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: projectradar-postgres
    environment:
      POSTGRES_DB: projectradar
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user) -d projectradar"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - projectradar-network

  rabbitmq:
    image: rabbitmq:4.1.2-management-alpine
    container_name: projectradar-rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./dev-secrets/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - projectradar-network

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  projectradar-network:
    driver: bridge